version: "2"
services:
  express-exam-db:
    container_name: express-exam-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "database"
      MYSQL_PASSWORD: "toor"
      MYSQL_ROOT_PASSWORD: "toor"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - express-exam-db-data:/var/lib/mysql
    networks:
      inner:
        aliases:
          - express-exam-db
  express-exam:
    container_name: express-exam
    build:
      context: ./
      dockerfile: Dockerfile.development
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - express-exam-db
    volumes:
      - "./:/usr/src/app"
      - "~/.ssh:/root/.ssh"
    networks:
      inner:
        aliases:
          - express-exam
networks:
  inner: {}
volumes:
  express-exam-db-data: {}
